@echo off
echo Uploading brand...
curl -i -X PUT -H "apikey: sb_publishable_3DWLrcWUpjuE_gNKEivM8A_UHOmJLgu" -H "Authorization: Bearer sb_publishable_3DWLrcWUpjuE_gNKEivM8A_UHOmJLgu" -H "Content-Type: image/png" --data-binary "@C:\Users\Akimkhan\.gemini\antigravity-ide\brain\07a96865-b649-432d-b059-a80ccf3adab5\brand_art_1782888494260.png" "https://hniqpnuqqsmqpolxgbav.supabase.co/storage/v1/object/assets/services/brand.png"

echo Uploading industrial...
curl -i -X PUT -H "apikey: sb_publishable_3DWLrcWUpjuE_gNKEivM8A_UHOmJLgu" -H "Authorization: Bearer sb_publishable_3DWLrcWUpjuE_gNKEivM8A_UHOmJLgu" -H "Content-Type: image/png" --data-binary "@C:\Users\Akimkhan\.gemini\antigravity-ide\brain\07a96865-b649-432d-b059-a80ccf3adab5\industrial_art_1782888509629.png" "https://hniqpnuqqsmqpolxgbav.supabase.co/storage/v1/object/assets/services/industrial.png"

echo Uploading marketing...
curl -i -X PUT -H "apikey: sb_publishable_3DWLrcWUpjuE_gNKEivM8A_UHOmJLgu" -H "Authorization: Bearer sb_publishable_3DWLrcWUpjuE_gNKEivM8A_UHOmJLgu" -H "Content-Type: image/png" --data-binary "@C:\Users\Akimkhan\.gemini\antigravity-ide\brain\07a96865-b649-432d-b059-a80ccf3adab5\marketing_art_1782888520865.png" "https://hniqpnuqqsmqpolxgbav.supabase.co/storage/v1/object/assets/services/marketing.png"

echo Uploading concept...
curl -i -X PUT -H "apikey: sb_publishable_3DWLrcWUpjuE_gNKEivM8A_UHOmJLgu" -H "Authorization: Bearer sb_publishable_3DWLrcWUpjuE_gNKEivM8A_UHOmJLgu" -H "Content-Type: image/png" --data-binary "@C:\Users\Akimkhan\.gemini\antigravity-ide\brain\07a96865-b649-432d-b059-a80ccf3adab5\concept_art_1782888575330.png" "https://hniqpnuqqsmqpolxgbav.supabase.co/storage/v1/object/assets/services/concept.png"
